spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  social:
    facebook:
      app-id: 370860263035094
      app-secret: 1afeba84a17b230bbd7b264a5e63d863


